def build_matchup_features(home_features: dict, away_features: dict) -> dict:
    return {
        "home_last_10_win_pct": home_features["last_10_win_pct"],
        "away_last_10_win_pct": away_features["last_10_win_pct"],
        "last_10_win_pct_diff": home_features["last_10_win_pct"] - away_features["last_10_win_pct"],
        "home_avg_points_last_10": home_features["last_10_avg_points"],
        "away_avg_points_last_10": away_features["last_10_avg_points"],
        "avg_points_last_10_diff": home_features["last_10_avg_points"] - away_features["last_10_avg_points"],
        "home_avg_plus_minus_last_10": home_features["last_10_avg_plus_minus"],
        "away_avg_plus_minus_last_10": away_features["last_10_avg_plus_minus"],
        "avg_plus_minus_last_10_diff": (home_features["last_10_avg_plus_minus"] - away_features["last_10_avg_plus_minus"]),
        "home_season_win_pct": home_features["season_win_pct"],
        "away_season_win_pct": away_features["season_win_pct"],
        "season_win_pct_diff": home_features["season_win_pct"] - away_features["season_win_pct"],
        "season_avg_points_diff": home_features["season_avg_points"] - away_features["season_avg_points"],
        "season_avg_plus_minus_diff": home_features["season_avg_plus_minus"] - away_features["season_avg_plus_minus"],
        "home_rest_days": home_features["rest_days"],
        "away_rest_days": away_features["rest_days"],
        "rest_days_diff": home_features["rest_days"] - away_features["rest_days"],
        "home_back_to_back": home_features["is_back_to_back"],
        "away_back_to_back": away_features["is_back_to_back"],
    }
